{"name": "Invalid data", "status": "failed", "statusDetails": {"message": "AssertionError: Failed. Expected Epic sadface: Username and password do not match any user in this service, but actually got Epic sadface: Sorry, this user has been locked out.", "trace": "index_page = <pages.index_page.IndexPage object at 0x0000024006388160>, username = 'locked_out_user', password = '$(password)'\nexpected_result = 'Epic sadface: Sorry, this user has been locked out.'\n\n    @allure.description('Error message')\n    @allure.label('owner', 'Jenya')\n    @allure.title('Invalid data')\n    @allure.suite('Unsuccessful_login')\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.parametrize('username, password, expected_result', (case_1, case_2, case_3, case_4))\n    def test_unsuccessful_login(index_page, username, password, expected_result):\n        index_page.enter_wrong_username(username)\n        index_page.enter_password(password)\n        index_page.click_to_login_btn()\n>       index_page.check_error_message_container(expected_result)\n\ntests\\test_index_page.py:33: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\index_page.py:79: in check_error_message_container\n    self.check_equal(error_message, actual_result)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nactual_result = 'Epic sadface: Sorry, this user has been locked out.'\nexpected_result = 'Epic sadface: Username and password do not match any user in this service'\n\n    @staticmethod\n    def check_equal(actual_result, expected_result):\n>       assert actual_result == expected_result, AssertionErrors.EQUAL_ERROR.format(expected_result, actual_result)\nE       AssertionError: Failed. Expected Epic sadface: Username and password do not match any user in this service, but actually got Epic sadface: Sorry, this user has been locked out.\n\nsupport\\assertions.py:5: AssertionError"}, "description": "Error message", "steps": [{"name": "Enter wrong username", "status": "passed", "parameters": [{"name": "username", "value": "'locked_out_user'"}], "start": 1683695684075, "stop": 1683695684217}, {"name": "enter password", "status": "passed", "parameters": [{"name": "password", "value": "'$(password)'"}], "start": 1683695684217, "stop": 1683695684355}, {"name": "click to login btn", "status": "passed", "start": 1683695684355, "stop": 1683695684476}], "attachments": [{"name": "log", "source": "decf795f-38a3-4382-ae03-dd1480c492e1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'locked_out_user'"}, {"name": "password", "value": "'$(password)'"}, {"name": "expected_result", "value": "'Epic sadface: Sorry, this user has been locked out.'"}], "start": 1683695684075, "stop": 1683695684516, "uuid": "9d0655d2-5e2b-46ca-b658-1af6fa950fac", "historyId": "60fedf1271b3219a5fb8c160b97c965e", "testCaseId": "a7c18bc2d0a4e903f0cff3007abfbc12", "fullName": "tests.test_index_page#test_unsuccessful_login", "labels": [{"name": "suite", "value": "Unsuccessful_login"}, {"name": "owner", "value": "Jenya"}, {"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "DESKTOP-EPJBQ14"}, {"name": "thread", "value": "2248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_index_page"}]}